group: travis_latest
language: node_js
node_js: node
cache: yarn

branches:
  only:
    - master

templates:
  with_docker: &with_docker
    services:
      - docker

  with_browsers: &with_browsers
    addons:
      chrome: beta
      firefox: latest-beta

jobs:
  include:
  - stage: test
    <<: *with_docker
    <<: *with_browsers
    script: xvfb-run yarn test

  - stage: test
    <<: *with_docker
    <<: *with_browsers
    node_js: lts/*
    script: xvfb-run yarn test

  - stage: release
    env:
      - secure: YNeRBjBDCy1NqlepNGrZWq97/lL0iO7aoZt3jFX0+0YyKzQy2PGcgL3s0TmOcjG/24jtVCCnUCaSEaOomDpGLvWACFR91lFeYS7FNbBUBS713KSzbRlAq3GMF6BiNoQ2WMakSyv1LvgsM2IIhvmFiequSTP0pN7EcG4aqnVPlTQ96mbbI6U1IlcsO9KOCEoOzw7mmtZxIWENS3e1aWkoB/XoJatucYXeDZTz5/A+YdxBbyMHluMdg6lDfKHNNjec+BUHf21Wwtj0njRKzfIXSv//utlXDk0zH2EwBsZY97/CQG5wufvpEOiSzH29h6B09THgV1tVKUiqYpq4/CckmHqc1/7R2dvUQQsUawD7LcKjF0y5p80etO2L+VagCvEdmNj5Xuj/GGEMmwmG2Pb/PpqeEWL6xq+8ZMpo8q7ZILgd9EZ9q0rwUvFVsak/p3oJWr0zCaNdeXLAJ1jzMl4PwDXvlSc2dHUW0AnvPZffm6Fdmakcz/+AYxgl2P2MNq/bUiF10vQZ4uLRNrLRB7hAfx4ewKIC2EzxGGDHtBwsS6diZQ0H1dX/HonoLsUJhUcbayld9ZCiRvqlm9RBX8PXrTtVAWdb3wTFzu8Gwwxbx3bUDEt/naCdsxMgAaG7dzgL5hkcnNE08QUailvop6wOJMrRFiFGW0YUun3Bg1IScm0=
      - secure: VmazJoeinms5lgkkNlhdtlSWaHtEFSgjnnHYMlgM1KM9Cy2VuSa13ZgVKC8te3PruhDGOMOGgJlAk0wjzAqoYpF3rDouXSuQjoJos6jmXrs6+vtAeQ5sgQkhmSRcr4UHhhH7gyEzBGni/2T7ObWhdHLPfVfX/VjU7WXkWXjkHgaqoUqq1SsFIHlOqKdl7HBorYLxOsFZEkuZ6Tswt9M6clIOj6PDm9nUYHrp84fqQI3a/ck632PV+61fhheG+H1e/KrLx8tn6ORJhjVtTPsrXzt9vTuniOnmsMZoZ9mWQMRd643e1R24DIVl2XVx5dh4zeZpLDKV5ZRvOE+lhBdWvZLwiI26xPrJVbw7HWgt3ZRPZ1L6OMKWYjSbuaSvIohKemCJVyX03Kz8Rkb7HH7Mp8pIzOGSc4OroCCyqeU7/eA4x+ZjupbM/l+lqNNLgj8zxYFU3kLzf65e0GmbILNyhx0vIfOqlZHUPhuJYilZSUiLi6AMHOHLDkMStkFX29YNEDH1tYJuILfQ/rH0W/BQ83Z3zT8gyRegUmYg1XyyIfGPQpvvV4qmlF/fdqvC+4zZiDJtQe//eIbPJ0vzfC4QYSppQips69IOxDY7w7H6kQi0u14HF8EcvaiypnPUYbOcklCsYa/LtEliubUq2bv9NyJ3B/MSJ189JeQ3G86pDgY=
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: yarn release
