group: travis_latest
language: node_js
node_js: node
cache: yarn

templates:
  with_docker: &with_docker
    services:
      - docker

  with_chrome: &with_chrome
    addons:
      chrome: stable
    before_install:
      - export DISPLAY=:99.0
      - Xvfb :99 -screen 0 1280x800x24 &>/dev/null &

jobs:
  include:
  - stage: test
    <<: *with_docker
    <<: *with_chrome

  - stage: test
    <<: *with_docker
    <<: *with_chrome
    node_js: lts/*

  - stage: release
    env:
      - secure: ky7rktHV5s16OqU4vWfLLIk7Nin6oJdZfPgWibiaU6eNEQhfLuZH9UuANiaynWgx9UTqw6z6iRzXsD6OWPe4O9kct8jYcBZC4/6J1HsRf/J8UsSHtmWmY8nt790BYMTbALmOqX9Oa8MBcJAZjLDaBCQ4we1SpbN5/t1zKgc9kDSydBOgx1X9xsZOjsw4p0M/ALBpEmm17FQJwMy4V+UhNYy8ldyacfxjTOx27vVhR8FLAv+FSM4Nrggjfry71EmmtDxtR7DcHeXVVpn6H+hjiEbEl09JXdKRsGC8jiu9a8HK8/BM0aecCCexmiMDH8goP4al45RlOrLwWdJxJh5YKeY/ymHZnfq1KKUqQ0QBrK4q45UPo9xjoqWE4RrMPvfIh8V+ANO8oTNT1aqqfByilcTSd8dvL3mas7pG9V9rS23Gl9MtRWjHGAKu/gmsGC622GWTPGtTt+IzW0z1FAeKYYhkqh7ud/cORjdZSQ+s4bTZ/POqpxLXzOkTMgdrZ3q3CN/HBX1nSKNGgd2pd5PwdHgDZrks4Gnlb4M6Y05ZoyfpYhUxzlvtRu/BdxPG/4NDJ7rZxt6l599hRvfv+tLI6jK0NaLmleRKTWGDilXUbCAbR/2fTpNvNmV1A9yYQ8mQPBvYEej3xs5gsn12DDxqS2NcEUgi3Ks1Nx7pZIIlO/Y=
      - secure: b8ebUKS7EqZxjbqqtpyp0Do3OniVprwoVlDWl3TcGuGB1n231OExVzJHuFsmtg+Nafm3sYF8trE7MFw2XaXzfWSCeMfszRIs6hh+zNshtyCvsv0xPeLMZDxlQFqL27yGlwK7M+4RjVGmE7D23TUZ/hRHjXURHRnPB8EMzOkrBv9ypiuK781tM++71EOX0k7jfmk12FLVqN0lYJyunRbTxlaltPzZREZMXb366AkVsTaEr1M1IdO8xqeW5xNBCZOzBeZ6C9UZcvxXW0OOKCrBdhYAxO85AuVM05hT3nkKP6h1sLrjPjsomMyyh851BilTQoDbeB6CG5JC0SEs29IDn6tAC+/sshH/p6/KKuGgulM4YeyccpMDkGNh380f+ZOZNQ98uBSV2aNxp3Z54Ld35nSqiEhjrPIAbSg9Lbw0iPMD9JuvZB6cBDY3NnRakZUTqA2Y9y4/tvBqUA8KicVe3lWZjiNDCwJzR5zqBo4a7QYE0Gm6jCoh+HKbQrpzMAIW3Bw7dTnmSPLccP2UclUZlOgmN000gCHraJjh0DSB+5V8vPl7i0GP0rABr73IpKAVMWOpOpJy2wggk9kqh2dl5fpwtOsRMlBcAWnqbmQL3ONUSox8P/6Ldy8s4+YumjIWH/3Ze8p1COtXf7t/glSJcszyib27LRV1952uG6vV4gA=
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: yarn release
