group: travis_latest
language: node_js
node_js: node
cache: yarn

templates:
  with_docker: &with_docker
    services:
      - docker

  with_chrome: &with_chrome
    addons:
      chrome: stable
    before_install:
      - export DISPLAY=:99.0
      - Xvfb :99 -screen 0 1280x800x24 &>/dev/null &

jobs:
  include:
  - stage: test
    <<: *with_docker
    <<: *with_chrome

  - stage: test
    <<: *with_docker
    <<: *with_chrome
    node_js: lts/*

  - stage: release
    env:
      - secure: luFAmbgmUPTPK3KzynXYrnZ/VzWwERyG7pZsz4dmMyO5uBmV+nY+UR7ly90VEZyH6s9Xp5SAjNn9ldNSoheBD5d10HsFOSXB6pxru9TmeaPCHykImXmYayqJ3xcUm1bexa4x96H7XPXaoLwLZ209RDXdH0PAW7ZE74fH731ButydBIkD/BZo5mdMhCEyWKY9hiF7JKD1giIgAMT3RLpEZ5R2bB5FKemGtBjEuPxldrRHfDe34+LV+AgvJeq8WoBTX6e+NKhbACzvr1ipTWJ7F64fRl7dXtjjStnMU4Ws/sKjlbRCOIm3tY/qMPfqOFAUYUcUt5ZF3zafMj8c5B9M6VVkqLSyyEZ4RLAaO2lWlwlAc+PkLg7IoSfERNlbCTbrgLpYVw3QjUMKGuLFDt6uhZEVQ9gG3K4Y6BjfeOPqe5t1cUiZ2stU9QB0JaDg1Zl+tI/eZitya9+F7iUaVrEea8Ld6ZBtnAQ9JIVJE1GAnmmrJg2uFfgYqzChxMdRNkVMM2hHDVG1UvmpOtHdbazvJVHxar0l/v7XmxjW/WWsG03mtoO7Wy8ybB32qQ/saiy/RDKJBUGw+7K54c/nBCU/ZTUmzcizAalmXvmubeMknCrqSWWiIXFbmdMWkk6A493yhy6HbCToRQXsn7pfoh46ckhTqZUa+rQ/ioDKhGRrIro=
      - secure: VzLguGJ7HQNEvoGMV9swMXSyP1qxxVHZAr7iDpAfuugKm/pllOuwjjXdNkgUooLDoSlkxOqpvvMF1UrnjKSCZ8zA/OY0Br3MbZZmgIznSPtsInlba28w1ywE3E1jpppicqaoRoQwUWbiawByEt70l/j83XFxZ2QgjInJUn7+lk9JvXcevww2c6PsM7S7YETYl7icGr9f5+QWtkB4zcP5ZOAF94He5ieN3M4ShOQLHyEz8OBznUZMeGPECbBTttH32fAkpwMiPPf9OT+zVJa1XtGHNAgbMYWciJFURrTfiby4XvY548rnyBs2UCnAipMHAQm8PCn6HKrtx9wtqYskF8AvpRNDJiVTZSe/4xG1MNwAfd70/l9GeUpTpjYV3qfKSw9S8aRLlRA0ay7MYjSuvxEvsp4IFDOcmYpPmOa3GwsQRZ5U0Op6Cjcc/XNAL6enhDw5VLi8Ny5DgENN4Jz9bF2afrBcaSlxjN7zdwZkcVi1asr969lb58/LYrqF+LCuhTmHXSKLnETBzoTPa/Viu7uEI6F5bMciQkWye9ae+0JSImjpuCWQLmIkhFTvYEGL9Zmtu5ZbB1JEvVNsIk0J3/IC1GaA4RavW1PMcctRnGJB4KgXhDmEkizkue7Fg8w43xTdq8WvXlOdf9Iq3N19i1PO2MQDrsmVcRvgtk/KHAI=
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: yarn release
