group: travis_latest
addons:
  chrome: stable
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  'on':
    tags: true
  email:
    secure: >-
      WP8GGfCfSnUVyyHOzKZZOYIMg0E1yvhvLuolBj6PuX8c8peTB0a3xLzFgB80bUcbbcvVvamFbORR7bNWxBXAdBx5khVqdNCAt6mVvqnYVaF9/rgjNKyT0UDQbHAXLar7bSNHYB5i3rHSmPadVMoem9gI3chm0WG1a8Kh8iPbcgSenqlBfniE0IMi4wkNiTKJ2MCN7Z+EN53QmXi3vxIFbQvEmLIHNiucRzWSbZ9FduW5fEG63tpze1rNP3DvmzeoPS1DGhccjz0JSE8BEpceFNq9/lcU9X5humDE2qp7dwtgxO72QptbZTlgKKCwfbgv5AaVotMqemB94nxc3yvPDBjXuw/ZJ6LJd66YTpbwwvzgTl8yzU04QBt0xzVvK2Nzo7Qq3FPBuoIlymC1HjY/4Ih6O38T6fGYk20Vk866yvNLInCQTilLB3tZxAFKdLGP3J7GvDNXjEJPIZXNmfcyTxGaAuiH+yRJCaW0DIDrVvRUxef0SefEG/KsxaI8xxyqrP3BP/ho3VI/S9U7N0Bw6/dZoP7JfLCuptcYs7IqB+TMXYCFtWVtIMpijFycUuG6uPeret6POEpH5PClSc7B2LYPQajXTqTBPcyaaB4tnImjAWyYBgI/dTYA6tdEbYQ4rOCYFMGMqfNBMvtz/e/YES1r/teJGkA4BAgzzwTdmbI=
  api_key:
    secure: >-
      fyrRVhZn+ACYM+DWuZeTuc/uQhprHqEPHEKQBYk+MgUtZ3rBhrxAkoLFJxy0fFQ2TGDJtortMrpj8GDmD1ksYe0dfgfE8nc87BWmO6b5yDz9RvbuQwDM8mzUY2l1Hb/i+BA8QVT6kHPvrziJmkLV1DZh4yz1C4XtEYRJLU530KWISBoOvB0IETAKOsWdE1BLC07GOg9g/76SvbWumyPZElEH5282BTwk6r84qEwXmWC0/cCV3UQOUSBzKoJjNck28zftdvAksAwUCAUwbRgDCrF9l616QmjTsAhZ3OlQfT+kgQCOlQEeQEBQbBQPAnrgBE0nV4cSTx2eNdO5DCrumpacgyTJlrr/iN10xjcYbYTtiFrXSlG6S1zDmf1s0zu++GtXjG2myXDK2krkca+aGBLvu2uawWIcdAc+XMpVcJR3PRPv7X26FayEy6S/bgMAt74jqGe68t30kmRf7lLVYJXJseuDL+AkKfWgsHFD/JVFeow5deUC4yxaXrO0EgMSSXBOxfb7dNSf/kmV37C3/uS52Y5FSKmo6Dt+s9hEPAQDF8HN+ujUOPh2SsMXg/mvVe/XgJQqYmrT3Xd15VxyjSEKve85mi9X8kgXcd6DD4I6xojSsuIlRK/PC3t9jqDHd/7EPrtA9L9ouFnxDADHS+B3Xm0Bx3qLhce5E8IWRgI=
